### ISSUE TITLE
Manual code review

### ISSUE THREAD

**Issue by arpadfodor** [BME-MIT-IET/Rdfs-team-iet-2019#4]
Return value of DatabaseAdapter/updateRecord and DatabaseAdapter/updateRecords are never used. 

- eliminate unused return values of updateRecord/updateRecords
- update method descriptions

Fixed in https://github.com/BME-MIT-IET/Rdfs-team-iet-2019/commit/a7b73efff9bca53504b3e1e41d763b07eee43985

**Comment by arpadfodor** [comment]
In ExportAsyncTask/getFileLastModifiedTimestamp the timestamp value (Long) is divided by a constant value of 1000 to convert from milliseconds to seconds. As type Long is nullable, it can lead to null/1000 division.

- change from Long to primitive long to prohibit null values
- add method description

Fixed in https://github.com/BME-MIT-IET/Rdfs-team-iet-2019/commit/189404530f2a1d01d3a4db0cb2242bb0095c1693

**Comment by arpadfodor** [comment]
Price/Reduce method is too complicated and lacks description header. Thus hardly interpretable.

- add description to method, add comment to the complex parts

Fixed in https://github.com/BME-MIT-IET/Rdfs-team-iet-2019/commit/bc60c8aa5c2c76c1c24afd1e91a68e8553e78d00

**Comment by arpadfodor** [comment]
Recurrence/setPeriodEnd function has legacy code part which is not used anymore. Labelled not good by the developer, but not deleted. Unused imports exist in the file.

- remove unused legacy code
- get rid of unused imports

Fixed in https://github.com/BME-MIT-IET/Rdfs-team-iet-2019/commit/ce2e099f54bf03e31c82e0469780e580c2e27dae

**Comment by arpadfodor** [comment]
Split/equals and Split/isEquivalentTo functions has the same 10 lines of code. That boilerplate code is hardly readable and the functions are complicated. The functions are labelled with @SuppressWarnings("SimplifiableIfStatement").

- outsource boilerplate code
- add description to new function

Fixed in https://github.com/BME-MIT-IET/Rdfs-team-iet-2019/commit/abd570c1a505a2ffc36df00e44fefe6da124a01e

**Comment by arpadfodor** [comment]
CommoditiesCursorAdapter has unnecessary TextView cast in bindView.

- remove redundant cast

Fixed in https://github.com/BME-MIT-IET/Rdfs-team-iet-2019/commit/e8945deef4cc0c01a3c1222ef564f564719fd404

**Comment by arpadfodor** [comment]
AccountsActivity checks whether the current session is the first run of the app on the current device or not. This check can block the main thread as commit() is called on a SharedPreferences Editor in the main thread.

- call apply instead of commit (apply commits asynchronously)

Fixed in https://github.com/BME-MIT-IET/Rdfs-team-iet-2019/commit/2d06a6ebdc0d48cc274de32c55170a5e0379202e

**Comment by arpadfodor** [comment]
Interface OnAccountClickedListener has accountSelected method labelled as public. Since the interface is labelled public too, this method prefix is redundant. An interface labelled public has only public methods.

- remove redundant prefix

Fixed in https://github.com/BME-MIT-IET/Rdfs-team-iet-2019/commit/053332075e3a9fb0211e6478fd01c613bf5ed0ad

**Comment by arpadfodor** [comment]
PreferenceActivity has a one-way switch statement which is needless and slow.

- change one-way switch to if statement

Fixed in https://github.com/BME-MIT-IET/Rdfs-team-iet-2019/commit/0c130799a6f380aeb1ea4d8708bfaffe76359800

**Comment by kisborda** [comment]
Checked the changes, no problems found. Closing the issue.

**Comment by hpleesz** [comment]
Pull request: https://github.com/BME-MIT-IET/Rdfs-team-iet-2019/pull/5
