### ISSUE TITLE
Manuális tesztek megtervezése, végrehajtása és dokumentálása

### ISSUE THREAD

**Issue by adamsza** [BME-MIT-IET/Rdfs-team-iet-2019#6]
Funkcionális tesztek
UI tesztek
Interfész tesztek

**Comment by adamsza** [comment]
### Funkcionális teszt tervezet az elvégzendő tesztekről:

**A készítők által összeállított listából:**

- Chart of Accounts: Egy fő fiók rendelkezhet mellékfiókokkal. A különböző típusú fiókok egy fő fiókba csoportosíthatóak.

- Split Transactions: Egy tranzakció szétszedhető több részre.

- Double Entry: A tranzakciónak az egyik fiókból elvenniük kell, egy másik fiókhoz pedig hozzáadniuk. Így a bevétel és kiadás különbségének meg kell adnia a teljes vagyont.

- Income/Expense Account Types (Categories): Vannak fiókok, melyek bevételt jelenítenek meg és vannak melyek kiadást. Használhatóak double-entry-vel egy-egy nyereség&veszteséges állítás meghatározásához.

- Scheduled Transactions: Automatikus tranzakció létrehozása.

- Reports: Az összesített tranzakciók diagramon megtekinthetőek.

**Ezeken felüliek:**

- Kedvencekhez adás megfelelően működik.

- Egy felvett fiók megjelenik az alfiókban.

- Tranzakciók bevételei/kiadásai megjelennek a fiókban.

**Comment by adamsza** [comment]
A tesztek végrehajtása ebben a pdf-ben van dokumentálva: 
[Funkcionális tesztek](https://github.com/BME-MIT-IET/Rdfs-team-iet-2019/files/3170131/Funkcionalis.tesztek.pdf)

**Comment by adamsza** [comment]
### Tervezett UI tesztek:

- A listák vizsgálata

- Repot nézet és diagramok vizsgálata

- Beállítások oldal átnézése

- Menük átnézése

- Fragmentek vizsgálata

**Comment by adamsza** [comment]
A UI tesztek végrehajtásának dokumentálását tartalmazó pdf: 
[UI teszek.pdf](https://github.com/BME-MIT-IET/Rdfs-team-iet-2019/files/3170437/UI.teszek.pdf)

**Comment by adamsza** [comment]
### Elvégzendő interfész tesztek:

- Fájl exportálás csv, qif és xml formátumokba

- Importálás az előző formátumokból

**Comment by adamsza** [comment]
### Interfész tesztek:
# Exportálás:
Az export to paraméternél save as… opciót választva az  alkalmazás sikeresen kiexportálja a tranzakciókat mind a három fájlformátumba.
# Importálás:
Olvasni azonban a kiexportált fájlokból csak az xml végű fájlokat képes.

**Comment by adamsza** [comment]
## Telepítési tesztelés

**Comment by adamsza** [comment]
### Telepítési tesztelés:
#### Az alkalamazás telepítése:
Az alkalmazás gond nélkül telepíthető egyaránt az áruházból és kódból is
#### Az alkalmazás törlése:
Az alkalmazás eltávolítása sikeres volt, látható nyomot nem hagyott a rendszeren (a tárhelyen lévő adatok is eltávolításra kerültek.

**Comment by hpleesz** [comment]
A teszttervezeteket rendben találtam, a végrehajtás megfelelően lett dokumentálva.
