### ISSUE TITLE
Tesztek kódlefedettségénék mérése és a tesztkészlet bővítése

### ISSUE THREAD

**Issue by hpleesz** [BME-MIT-IET/Rdfs-team-iet-2019#7]
A projektben már meglévő tesztek futtatása, kódlefedettség mérése és több teszt hozzáadása.

**Comment by hpleesz** [comment]
Android studio-ban a a meglévő teszteket futtattam. 141 tesztből mind helyesen lefutott.
![Screen Shot 2019-05-18 at 12 49 51](https://user-images.githubusercontent.com/37176624/57968479-82892b80-796b-11e9-80fe-6c8de8a54860.png)
A tesztek kódlefedettsége:
![Screen Shot 2019-05-18 at 1 07 16](https://user-images.githubusercontent.com/37176624/57968493-93d23800-796b-11e9-972a-07885748adb8.png)

**Comment by hpleesz** [comment]
AccountsDbAdapter updateAccount és updateAllAccounts függvények tesztelése.
commit: https://github.com/BME-MIT-IET/Rdfs-team-iet-2019/commit/06fb26026d4c32e951a5c6b098420673e48c0072 és https://github.com/BME-MIT-IET/Rdfs-team-iet-2019/commit/d75fe2d68f74885014806c6b96c0bd0025cc48ea

**Comment by hpleesz** [comment]
AccountsDbAdapter getAccountColorCode függvény tesztelése.
commit: https://github.com/BME-MIT-IET/Rdfs-team-iet-2019/commit/7fb42b369e4b6f3a7b9be38a29f549df97057a74

**Comment by hpleesz** [comment]
AccountsDbAdapter getOrCreateOpeningAccountUID függvény tesztelése ha nincs még opening account.
commit: https://github.com/BME-MIT-IET/Rdfs-team-iet-2019/commit/48f965e5ab5241a5df44a597159d3818371de0f7

**Comment by kisborda** [comment]
BooksDbAdapter getActiveBookDisplayName() függvény tesztelése
commit: b44c1b3
Account convertToOfxAccountType függvény tesztek
commit: 6f6b1ad
Budget függvények tesztjei
commit: e0276e6

**Comment by kisborda** [comment]
Még két teszt a Budget osztályhoz.  a8edde8
Money withCurrency függvény teszje:  21a4696
Split osztályhoz tesztek  8e126bb
Transaction shouldDecreaseBalance, setUID, getTypeForBalance függvébyeinek tesztje  ce463ec

**Comment by hpleesz** [comment]
Pull request: https://github.com/BME-MIT-IET/Rdfs-team-iet-2019/pull/8
